name: PolymerSeq
channels:
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - pandas
  - anaconda::scikit-learn
  - h5py
  - conda-forge::pyyaml
  - pip
  - pip:
      - torch==2.6.0+cu118
      - --extra-index-url https://download.pytorch.org/whl/cu118
